export const MAIN_IMAGE = [
  { name: "project0Chapter", path: "" },
  { name: "project1Chapter", path: "" },
  {
    name: "project2Chapter",
    path: "/img/mainoltlab.png",
    width: "166px",
    height: "496px",
  },
  {
    name: "project3Chapter",
    path: "/img/maintlo.png",
    width: "166px",
    height: "496px",
  },
  {
    name: "project4Chapter",
    path: "/img/mainenojy.png",
    width: "166px",
    height: "496px",
  },
  {
    name: "project29Chapter",
    path: "/img/mainpl_3d_145_2024.png",
    width: "247px",
    height: "134px",
  },
  {
    name: "project28Chapter",
    path: "/img/mainfr_3d_gtobc_2024.png",
    width: "312px",
    height: "220px",
  },
  {
    name: "project27Chapter",
    path: "/img/mainfr_arch_pom_2024.png",
    width: "235px",
    height: "292px",
  },
  {
    name: "project26Chapter",
    path: "/img/mainpl_urb_kat_2024.png",
    width: "235px",
    height: "292px",
  },
  {
    name: "project25Chapter",
    path: "/img/mainfr_arch_conc_2024.png",
    width: "235px",
    height: "292px",
  },
  {
    name: "project24Chapter",
    path: "/img/mainprojects.png",
    width: "235px",
    height: "292px",
  },
  {
    name: "project23Chapter",
    path: "/img/mainbelgrade.png",
    width: "235px",
    height: "292px",
  },
  {
    name: "project22Chapter",
    path: "/img/mainadrianzert.png",
    width: "235px",
    height: "292px",
  },
  {
    name: "project21Chapter",
    path: "/img/main14by5.png",
    width: "235px",
    height: "292px",
  },
];
